In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)
result=[]
for i in a:
  result.append(i+2)
print("After adding 2 to each element:",result)
b=[]
for i in a:
  b.append(i*3)
print("After multiplying 3 with all the elements:",b)
c=np.divide(a,2)
print("After dividing every element by 2:",c)

[1 2 3 4 5]
After adding 2 to each element: [3, 4, 5, 6, 7]
After multiplying 3 with all the elements: [3, 6, 9, 12, 15]
After dividing every element by 2: [0.5 1.  1.5 2.  2.5]


In [ ]:
import numpy as np
a=np.array([1,2,3,6,4,5])
reverse=np.flip(a)
print("Reversed array:",reverse)
x=np.array([1,2,3,4,5,1,2,1,1,1])
print("Most frequent value in x array:",np.bincount(x).argmax())
print("All index value of 1 is:",np.where(x==1)[0])
y=np.array([1,1,1,2,3,4,2,4,3,3])
z=np.bincount(y)
maximum=max(z)
for i in range(len(z)):
  if z[i]==maximum:
    print("Most frequent value in y array:",i)
print("All index value of 1 is:",np.where(y==1)[0])
print("All index value of 3 is:",np.where(y==3)[0])

Reversed array: [5 4 6 3 2 1]
Most frequent value in x array: 1
All index value of 1 is: [0 5 7 8 9]
Most frequent value in y array: 1
Most frequent value in y array: 3
All index value of 1 is: [0 1 2]
All index value of 3 is: [4 8 9]


In [ ]:
import numpy as np
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr)
print("2nd element of 1st row:",arr[0,1])
print("1st element of 3rd row:",arr[2,0])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
2nd element of 1st row: 20
1st element of 3rd row: 70


In [ ]:
import numpy as np
vanshika=np.linspace(10,100,num=25)
print(vanshika)
print("Shape of the array:",vanshika.shape)
print("No. of dimensions of array:",vanshika.ndim)
print("Total elements:",vanshika.size)
print("Datatype of each element:",vanshika.dtype)
print("Total number of bytes consumed by the array:",vanshika.nbytes)
newarr=vanshika.reshape(25,1)
print(newarr)

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Shape of the array: (25,)
No. of dimensions of array: 1
Total elements: 25
Datatype of each element: float64
Total number of bytes consumed by the array: 200
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]


In [1]:
import numpy as np
ucs420_vanshika=np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
print(ucs420_vanshika)
print("Mean:",np.mean(ucs420_vanshika))
print("Median:",np.median(ucs420_vanshika))
print("Max:",np.max(ucs420_vanshika))
print("Min:",np.min(ucs420_vanshika))
print("Unique elements:",np.unique(ucs420_vanshika))
reshaped_ucs420_vanshika=ucs420_vanshika.reshape(4,3)
print("Reshaped array:",reshaped_ucs420_vanshika)
a=np.resize(ucs420_vanshika,(2,3))
print("Resized array:",a)

[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped array: [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized array: [[10 20 30]
 [40 50 60]]
